Added new/missing microbenchmarks for Aggregates,Joins and Orderby
yugabyte/benchbase pull request #103
Opened 2023-09-04 10:20 UTC by shantanugupta-yb

Added new/missing microbenchmarks for Aggregates,Joins and Orderby

2023-09-06 09:06 UTC, sonalsagarwal requested changes
Please check the review comments

2023-09-06 09:06 UTC, sonalsagarwal commented on config/yugabyte/regression_pipelines/aggregate_workloads/postgres/AGGRG10_aggregate_cardinality.yaml
> +                    customTags: schematype=colocated,pkey=composite,partition=hash,aggregate=count,cardinality=multiple,projection=aggregate,aggregateon=rangepkey,queryshape=aggregate,filteron=rangep
Do we add customTags for postgres?

2023-09-06 09:06 UTC, sonalsagarwal commented on config/yugabyte/regression_pipelines/aggregate_workloads/yb_colocated/AGGRG10_aggregate_cardinality.yaml
> +                    customTags: schematype=colocated,pkey=composite,partition=hash,aggregate=count,cardinality=multiple,projection=aggregate,aggregateon=rangepkey,queryshape=aggregate,filteron=rangep
partition should be range

2023-09-07 06:39 UTC, sonalsagarwal commented on config/yugabyte/regression_pipelines/join_workloads/yb_colocated/JOING9_cascadded_joins.yaml
> +                    customTags: schematype=colocated,partition=range,pkey=composite,cardinality=multiple,projection=indexed,filtercount=one,filteron=rangepkey,filtertype=subquery,queryshape=join,join
filtertype should be in

2023-09-07 06:40 UTC, sonalsagarwal commented on config/yugabyte/regression_pipelines/join_workloads/yb_colocated/JOING9_cascadded_joins.yaml
> +                        customTags: schematype=colocated,partition=range,pkey=composite,cardinality=multiple,projection=indexed,filtercount=one,filteron=rangepkey,filtertype=subquery,queryshape=join,
filtertype should be IN

2023-09-12 10:23 UTC, shantanugupta-yb commented on config/yugabyte/regression_pipelines/aggregate_workloads/postgres/AGGRG10_aggregate_cardinality.yaml
> +                    customTags: schematype=colocated,pkey=composite,partition=hash,aggregate=count,cardinality=multiple,projection=aggregate,aggregateon=rangepkey,queryshape=aggregate,filteron=rangep
Removed it

2023-09-18 11:11 UTC, sonalsagarwal approved these changes
LGTM

2023-09-20 10:44 UTC, merged