Add new IN queries scan tests
yugabyte/benchbase pull request #108
Opened 2023-09-28 14:19 UTC by timothy-e

* Update scanG4 to include 10k case for `yugabyte`, `yb_colocated`, and `postgres`
* Add scanG13 for IN queries with additional projected column

2023-10-13 05:53 UTC, shantanugupta-yb commented on config/yugabyte/regression_pipelines/scan_workloads/yugabyte/scanG13_pkey_rangeScan_INclause_with_tableCol_increasingRows.yaml
> +              customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projection=indexed,filtercount=one,filteron=rangeskey,filtertype=IN,queryshape=scan
Change custom tag projection to multiple, since we are projecting more than single indexed column. Please make changes in other files and workloads

2023-10-13 07:27 UTC, shantanugupta-yb requested changes
@timothy-e I have requested for few changes:
1. Change the name of the YAMLs goal number, it should be in the sequence of goals we have for a query shape. This should reflect in workload name as well.
2. The newly added YAML for colocated tables is missing "createdb" tag

2023-10-13 07:27 UTC, shantanugupta-yb commented on config/yugabyte/regression_pipelines/scan_workloads/yb_colocated/scanG13_pkey_rangeScan_INclause_with_tableCol_increasingRows.yaml
> +url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
Below tag is missing which creates a colocated database

> createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true

2023-10-17 04:50 UTC, shantanugupta-yb requested changes

2023-10-17 04:50 UTC, shantanugupta-yb commented on config/yugabyte/regression_pipelines/scan_workloads/yugabyte/scanG11_pkey_rangeScan_INclause_project_indexed_nonindexed_cols.yaml
> +            - workload: scanG13_pkey_INclause_rangescan_increasing_rows_1row
The workload name prefix should also be changed from scanG13 to scanG11 for all workloads in all 3 files.

2023-10-18 09:29 UTC, hbhanawat commented
@shaharuk-yb @chahatagrawal117 Can one of you please trigger the experiments with the new YAML files before they are merged to the master?

2023-10-19 05:29 UTC, hbhanawat approved these changes
Approving it since Shantanu is out and the test runs look good.

2023-10-19 05:30 UTC, merged