Indexfix
yugabyte/benchbase pull request #80
Opened 2023-04-12 04:50 UTC by shantanugupta-yb

2023-04-13 07:00 UTC, shaharuk-yb requested changes
Can we rename dir yb_regular to yugabyte to have it consistent across all folders. Existing folders use, yugabyte.

need to remove use_dist_in_explain=true in some postgres yamls. It is not supported in postgres

2023-04-13 07:14 UTC, shantanugupta-yb commented on config/yugabyte/orderby_workloads/postgres/ORDG5_pg_impact_of_datatype_with_sec_ind_desc.yaml
> +use_dist_in_explain : true
Removed

2023-04-13 07:14 UTC, shantanugupta-yb commented on config/yugabyte/orderby_workloads/postgres/ORDG6_pg_impact_of_increasing_rows.yaml
> +use_dist_in_explain : true
Removed

2023-04-18 06:59 UTC, hbhanawat approved these changes
Looks good. Please fix Shaharuk's comments before merging.

2023-04-19 06:29 UTC, shaharuk-yb approved these changes
LGTM

2023-04-19 06:32 UTC, merged